// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLKe1vKSCJ7QpJrfO8q_HlB6nXrm45c6g',
    appId: '1:399702781256:web:b26ac20e359c2472a4d77d',
    messagingSenderId: '399702781256',
    projectId: 'assuregroupapp',
    authDomain: 'assuregroupapp.firebaseapp.com',
    storageBucket: 'assuregroupapp.appspot.com',
    measurementId: 'G-D3QXWPX1DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLb-XFe0a-j-ywMM_VUhWxotPvqA6bFo',
    appId: '1:399702781256:android:a89895b82b6ca61ca4d77d',
    messagingSenderId: '399702781256',
    projectId: 'assuregroupapp',
    storageBucket: 'assuregroupapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRvPTgmea8kGdPyM-DhoTspz3yZQZOxU',
    appId: '1:399702781256:ios:934756347dc501e7a4d77d',
    messagingSenderId: '399702781256',
    projectId: 'assuregroupapp',
    storageBucket: 'assuregroupapp.appspot.com',
    iosBundleId: 'com.example.assureApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRvPTgmea8kGdPyM-DhoTspz3yZQZOxU',
    appId: '1:399702781256:ios:934756347dc501e7a4d77d',
    messagingSenderId: '399702781256',
    projectId: 'assuregroupapp',
    storageBucket: 'assuregroupapp.appspot.com',
    iosBundleId: 'com.example.assureApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLKe1vKSCJ7QpJrfO8q_HlB6nXrm45c6g',
    appId: '1:399702781256:web:34188d2f6b049a3fa4d77d',
    messagingSenderId: '399702781256',
    projectId: 'assuregroupapp',
    authDomain: 'assuregroupapp.firebaseapp.com',
    storageBucket: 'assuregroupapp.appspot.com',
    measurementId: 'G-08CXRR6TNH',
  );

}